"""Initial schema with all tables

Revision ID: 7807caff4d60
Revises: 
Create Date: 2026-01-26 16:51:44.773727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7807caff4d60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_with_school', sa.Boolean(), nullable=False),
    sa.Column('source_list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_is_default'), 'lists', ['is_default'], unique=False)
    op.create_index(op.f('ix_lists_share_token'), 'lists', ['share_token'], unique=True)
    op.create_table('adjectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjectives_list_id'), 'adjectives', ['list_id'], unique=False)
    op.create_index(op.f('ix_adjectives_order_index'), 'adjectives', ['order_index'], unique=False)
    op.create_table('analytics_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('is_standard_list', sa.Boolean(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_sessions_is_standard_list'), 'analytics_sessions', ['is_standard_list'], unique=False)
    op.create_index(op.f('ix_analytics_sessions_started_at'), 'analytics_sessions', ['started_at'], unique=False)
    op.create_table('analytics_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('adjective_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("bucket IN ('selten', 'manchmal', 'oft')", name='check_bucket'),
    sa.ForeignKeyConstraint(['adjective_id'], ['adjectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['analytics_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_assignments_adjective_id'), 'analytics_assignments', ['adjective_id'], unique=False)
    op.create_index(op.f('ix_analytics_assignments_bucket'), 'analytics_assignments', ['bucket'], unique=False)
    op.create_index(op.f('ix_analytics_assignments_session_id'), 'analytics_assignments', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_assignments_session_id'), table_name='analytics_assignments')
    op.drop_index(op.f('ix_analytics_assignments_bucket'), table_name='analytics_assignments')
    op.drop_index(op.f('ix_analytics_assignments_adjective_id'), table_name='analytics_assignments')
    op.drop_table('analytics_assignments')
    op.drop_index(op.f('ix_analytics_sessions_started_at'), table_name='analytics_sessions')
    op.drop_index(op.f('ix_analytics_sessions_is_standard_list'), table_name='analytics_sessions')
    op.drop_table('analytics_sessions')
    op.drop_index(op.f('ix_adjectives_order_index'), table_name='adjectives')
    op.drop_index(op.f('ix_adjectives_list_id'), table_name='adjectives')
    op.drop_table('adjectives')
    op.drop_index(op.f('ix_lists_share_token'), table_name='lists')
    op.drop_index(op.f('ix_lists_is_default'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
